# Generated by Django 2.2.5 on 2019-09-23 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herois',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('fraqueza', models.CharField(max_length=255, verbose_name='fraqueza')),
                ('universo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Universo')),
            ],
        ),
    ]
