# Generated by Django 2.2.5 on 2019-09-23 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_herois'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herois',
            old_name='universo_id',
            new_name='universo',
        ),
        migrations.AlterField(
            model_name='herois',
            name='universo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Universo'),
        ),
    ]
