# Generated by Django 2.2.5 on 2019-09-23 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20190923_2028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Herois',
            new_name='Heroi',
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab_heroi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Habilidade', to='landing.Heroi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arg_vilao',
            name='universo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Universo'),
        ),
        migrations.AlterField(
            model_name='heroi',
            name='universo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Universo'),
        ),
    ]
