# Generated by Django 2.2.5 on 2019-09-23 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20190923_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='arg_vilao',
            name='hab_vilao',
            field=models.ManyToManyField(related_name='Arg_vilao', to='landing.Habilidade'),
        ),
        migrations.AlterField(
            model_name='arg_vilao',
            name='universo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Universo'),
        ),
        migrations.AlterField(
            model_name='heroi',
            name='universo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Universo'),
        ),
    ]
